FROM ros:humble-ros-base

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install -y --no-install-recommends \	
    git \
    python3-pip \
    nano \
    software-properties-common \
    wget \
    python3-colcon-common-extensions \
    pkg-config \
    geographiclib-tools \
    libgeographic-dev \
    libeigen-stl-containers-dev \
    ros-humble-sensor-msgs \
    ros-humble-geographic-info \
    ros-humble-diagnostics \
    libasio-dev

RUN pip install future lxml

# RUN ros2 run mavros install_geographiclib_datasets.sh
RUN wget https://raw.githubusercontent.com/mavlink/mavros/ros2/mavros/scripts/install_geographiclib_datasets.sh 
RUN chmod +x install_geographiclib_datasets.sh
RUN ./install_geographiclib_datasets.sh

WORKDIR /usr/src/mavros_ws
RUN git clone https://github.com/ros2-gbp/mavlink-gbp-release.git --branch release/jazzy/mavlink ./src/mavlink
RUN git clone https://github.com/MAVTech-srl/mavros.git --branch ros2 ./src/mavros

RUN . /opt/ros/humble/setup.sh && colcon build

ENV SHELL="/bin/bash"

COPY ./mavros_entrypoint.sh /
ENTRYPOINT [ "/bin/bash", "/mavros_entrypoint.sh" ]
CMD ["bash"]